### ISSUE TITLE
Update homeAssistant matcher

### ISSUE THREAD

**Issue by CeeWeasel** [lukas-tr/vscode-materialdesignicons-intellisense#21]
Home Assistant has MDI icons baked into it, but use a prefix of hass. They are referenced in yaml files like this:

```
great_room_motion:
  icon: hass:walk
  name: Great Room Motion
  entities:
    - binary_sensor.great_room_motion
```

Changing the homeAssistant matcher as below ensures that the icons are found and inserted properly.

```
        {
            "match": "\\bhass:{param}\\b",
            "insert": "hass:{param}",
            "displayName": "Home Assistant",
            "name": "homeAssistant"
        }
```
Users can still use the kebabCase to match icons referenced as ```icon: mdi:walk```, but updating the homeAssistant matcher will also catch users that leverage Home Assistant's baked in icons.
